name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # This won't run on your local Windows machine

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test

    - name: Push to Local Registry
      env:
        DOCKER_REGISTRY: "197.27.249.161:5000"  # Use localhost for local testing
        IMAGE_NAME: "test"
      run: |
        docker tag test $DOCKER_REGISTRY/$IMAGE_NAME
        docker push $DOCKER_REGISTRY/$IMAGE_NAME
